<a href="https://colab.research.google.com/github/aylingunay/W-Code-2.0-Veri-Bilimi-ve-Yapay-Zeka-Atolyesi/blob/main/5_hafta%C3%96dev_AYL%C4%B0N_G%C3%9CNAY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1 boyutlu array oluştur
arr1 = np.array([4, 7, 2, 9, 1, 5], dtype=int)

# Boyut ve eleman sayısı
print("Array:", arr1)
print("Boyut (ndim):", arr1.ndim)
print("Eleman sayısı (size):", arr1.size)
print("Şekil (shape):", arr1.shape)


Array: [4 7 2 9 1 5]
Boyut (ndim): 1
Eleman sayısı (size): 6
Şekil (shape): (6,)


In [2]:
# 2 boyutlu array
arr2 = np.array([[1, 2, 6, 7],
                 [4, 3, 9, 5]])

# 3 boyutlu array
arr3 = np.array([[[7, 5, 14], [21, 8, 11]],
                 [[8, 6, 20], [14, 3, 9]]])

# İki boyutlu array bilgileri
print("\nİki boyutlu array:\n", arr2)
print("Boyut:", arr2.ndim)
print("Şekil (satır, sütun):", arr2.shape)
print("Eleman sayısı:", arr2.size)

# Üç boyutlu array bilgileri
print("\nÜç boyutlu array:\n", arr3)
print("Boyut:", arr3.ndim)
print("Şekil:", arr3.shape)
print("Eleman sayısı:", arr3.size)



İki boyutlu array:
 [[1 2 6 7]
 [4 3 9 5]]
Boyut: 2
Şekil (satır, sütun): (2, 4)
Eleman sayısı: 8

Üç boyutlu array:
 [[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
Boyut: 3
Şekil: (2, 2, 3)
Eleman sayısı: 12


In [3]:
# 2 boyutlu arrayden eleman çekme
print("\narr2[0,1] (2):", arr2[0,1])     # 2
print("arr2[0,3] (7):", arr2[0,3])       # 7

# 3 boyutlu arrayden eleman çekme
print("arr3[1,1,2] (9):", arr3[1,1,2])   # 9
print("arr3[0,0,1] (5):", arr3[0,0,1])   # 5



arr2[0,1] (2): 2
arr2[0,3] (7): 7
arr3[1,1,2] (9): 9
arr3[0,0,1] (5): 5


In [4]:
# 2 boyutlu array
print("\narr2[0,1:3] (2,6):", arr2[0,1:3])     # 2,6
print("arr2[1,1:] (3,9,5):", arr2[1,1:])       # 3,9,5

# 3 boyutlu array
print("arr3[0,1,:] (21,8,11):", arr3[0,1,:])   # 21,8,11
print("arr3[1,0,1:3] (6,20):", arr3[1,0,1:3])  # 6,20



arr2[0,1:3] (2,6): [2 6]
arr2[1,1:] (3,9,5): [3 9 5]
arr3[0,1,:] (21,8,11): [21  8 11]
arr3[1,0,1:3] (6,20): [ 6 20]


In [5]:
# 5x3 boyutlu sıfır ve bir arrayleri
zeros_arr = np.zeros((5, 3), dtype=int)
ones_arr = np.ones((5, 3), dtype=int)

# Satır bazında birleştirme (alt alta)
concat_rows = np.vstack((zeros_arr, ones_arr))

# Sütun bazında birleştirme (yan yana)
concat_cols = np.hstack((zeros_arr, ones_arr))

print("\nSatır bazında birleştirme:\n", concat_rows)
print("Sütun bazında birleştirme:\n", concat_cols)



Satır bazında birleştirme:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Sütun bazında birleştirme:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
